# Generated by Django 4.1.7 on 2023-04-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="member",
            field=models.BooleanField(default=True),
        ),
    ]
