# Generated by Django 4.1.7 on 2023-04-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="member",
        ),
    ]
